apiVersion: apps/v1
kind: Deployment
metadata:
  name: danne-deployment
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: danjan7903/webserver-docker:latest
        ports:
        - containerPort: 80